# Generated by Django 3.0.6 on 2020-05-29 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
