# Generated by Django 3.0.6 on 2020-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_paypalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payPalID',
            field=models.CharField(max_length=100),
        ),
    ]
