# Generated by Django 3.0.6 on 2020-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200527_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payPalID',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Almaty', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='classification',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Kazakhstan', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
