# Generated by Django 3.0.6 on 2020-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200522_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pledgeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
