# Generated by Django 3.0.6 on 2020-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200526_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('it', 'IT'), ('sport', 'Sport'), ('health', 'Health'), ('electronic', 'Electronic'), ('transport', 'Transport'), ('culture', 'Culture'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
