# Generated by Django 3.0.6 on 2020-05-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200531_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='post.Post'),
        ),
    ]
