# Generated by Django 3.0.6 on 2020-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='portfolioImages/default.png', upload_to='portfolioImages'),
        ),
    ]
