# Generated by Django 3.0.6 on 2020-05-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('it', 'Информационные ТехнологииТ'), ('sport', 'Спорт'), ('health', 'Здоровье'), ('science', 'Наука и Техника'), ('electronic', 'Электроника'), ('transport', 'Транспорт и Логистика'), ('culture', 'Культура'), ('games', 'Игры и Развлечения'), ('food', 'Еда и Ремесло'), ('other', 'Прочее')], default='other', max_length=20),
        ),
    ]
